// <auto-generated />
using System;
using FamilyActivity.WebMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyActivity.WebMvc.Migrations
{
    [DbContext(typeof(WorkOrderDbContext))]
    [Migration("20231216180811_InitialWorkOrderDbPostgres")]
    partial class InitialWorkOrderDbPostgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rodzice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dzieci"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rodzina"
                        });
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            Name = "TATA"
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            Name = "MAMA"
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 2,
                            Name = "GOSIA"
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 2,
                            Name = "EMILKA"
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 3,
                            Name = "ALL"
                        });
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrdinalPriority")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Resource", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.Group", "Group")
                        .WithMany("Resources")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.WorkOrder", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Group", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
