// <auto-generated />
using System;
using FamilyActivity.WebMvc.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyActivity.WebMvc.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelPersonFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelPersonFamilyId");

                    b.ToTable("activiesDays", (string)null);
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelPersonFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonPicture")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("personFamilies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonName = 1,
                            PersonPicture = "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                        });
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.ModelPersonFamily", "ModelPersonFamily")
                        .WithMany()
                        .HasForeignKey("ModelPersonFamilyId");

                    b.Navigation("ModelPersonFamily");
                });
#pragma warning restore 612, 618
        }
    }
}
