// <auto-generated />
using System;
using FamilyActivity.WebMvc.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyActivity.WebMvc.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int?>("ModelPersonFamilyId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelPictureActivityId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ModelPersonFamilyId");

                    b.HasIndex("ModelPictureActivityId");

                    b.ToTable("activiesDays", (string)null);
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelPersonFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonName")
                        .HasColumnType("int");

                    b.Property<string>("PersonPicture")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("personFamilies", (string)null);
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelPictureActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityName")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("pictureActivities", (string)null);
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.ModelPersonFamily", "ModelPersonFamily")
                        .WithMany()
                        .HasForeignKey("ModelPersonFamilyId");

                    b.HasOne("FamilyActivity.WebMvc.Models.ModelPictureActivity", "ModelPictureActivity")
                        .WithMany()
                        .HasForeignKey("ModelPictureActivityId");

                    b.Navigation("ModelPersonFamily");

                    b.Navigation("ModelPictureActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
