// <auto-generated />
using System;
using FamilyActivity.WebMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyActivity.WebMvc.Migrations
{
    [DbContext(typeof(WorkOrderDbContext))]
    partial class WorkOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rodzice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dzieci"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rodzina"
                        });
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Resources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            Name = "TATA"
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            Name = "MAMA"
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 2,
                            Name = "GOSIA"
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 2,
                            Name = "EMILKA"
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 3,
                            Name = "ALL"
                        });
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrdinalPriority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Resource", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.Group", "Group")
                        .WithMany("Resources")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.WorkOrder", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.Group", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
