// <auto-generated />
using System;
using FamilyActivity.WebMvc.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyActivity.WebMvc.Migrations.PostgreSql
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231216174950_InitialDbPostgres")]
    partial class InitialDbPostgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int?>("ModelPersonFamilyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelPictureActivityId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ModelPersonFamilyId");

                    b.HasIndex("ModelPictureActivityId");

                    b.ToTable("ActiviesDays");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelPersonFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonName")
                        .HasColumnType("integer");

                    b.Property<string>("PersonPicture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonFamilies");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelPictureActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityName")
                        .HasColumnType("integer");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PictureActivities");
                });

            modelBuilder.Entity("FamilyActivity.WebMvc.Models.ModelActivityDays", b =>
                {
                    b.HasOne("FamilyActivity.WebMvc.Models.ModelPersonFamily", "ModelPersonFamily")
                        .WithMany()
                        .HasForeignKey("ModelPersonFamilyId");

                    b.HasOne("FamilyActivity.WebMvc.Models.ModelPictureActivity", "ModelPictureActivity")
                        .WithMany()
                        .HasForeignKey("ModelPictureActivityId");

                    b.Navigation("ModelPersonFamily");

                    b.Navigation("ModelPictureActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
